export const DEFAULT_QUESTIONS = new Set([
  "BAL hakkında genel bilgi ver",
  "Bornova Anadolu Lisesi müdürü kim?",
  "BAL'ın tarihçesi nedir?",
  "BAL ruhu nedir?",
  "Kampüste hangi imkânlar var?",
  "Hazırlık sınıfı nasıl?",
  "2025 LGS taban puanları nedir?",
  "Okula nasıl kayıt yapılır?",
  "BAL'a nakil şartları nelerdir?",
  "Dil bölümleri ve kontenjanları nasıl?",
  "Pansiyona nasıl başvurulur?",
  "Okulu ziyaret etmek için nasıl randevu alınır?",
  "YKS başarıları nasıl?",
  "Yabancı dil eğitimi nasıl?",
  "DSD programı nedir?",
  "DELF-DALF sınav merkezi ne demek?",
  "AP dersleri nelerdir?",
  "Bilim ve matematik olimpiyatları nasıl?",
  "Ayran Günü nedir?",
  "Hangi kulüp ve topluluklar var?",
  "BALÖDER nedir?",
  "BALEV bursu hakkında bilgi ver",
  "BALPOD nedir?",
  "Tiyatro, müzik ve spor faaliyetleri nasıl?",
  "Okula nasıl giderim?",
  "Hangi otobüsler okula gidiyor?",
  "Servis güzergâhları nelerdir?",
  "Ders giriş ve çıkış saatleri nedir?",
  "Okulun adresi ve telefonu nedir?",
  "Kampüs haritasına nereden ulaşabilirim?",
] as const);
